remote_theme: chrisrhymes/bulma-clean-theme:v0.14.0
title: Chess Kit
google_analytics: UA-4644630-2

defaults:
  - scope:
      path: ""
    values:
      hero_image: images/index_hero.jpg
      hero_darken: true
      twitter:
        card: summary_large_image
      image: images/index_hero.jpg
